### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by urbany** [leeoniya/uFuzzy#10]
Hi, thanks for this lib, it's working great.
Would be gret if you could add changelog with each version. You could maybe generate from your commits.

Thanks in advance!

**Comment by leeoniya** [comment]
not sure about changelogs pre-1.0, but nothing earth shattering/breaking in 0.8.0. mostly just tweaking `uFuzzy.highlight()` so it can be used with JSX/React and DOM elements instead of just strings (markdown/innerHTML). also added an option to opt out of splitting terms at camelcase and alpha-num boundaries (see https://github.com/leeoniya/uFuzzy/issues/9)

lazy changelog: https://github.com/leeoniya/uFuzzy/compare/0.7.0...0.8.0

**Comment by urbany** [comment]
@leeoniya that was a breaking change for me actually. I am customizing the highlight (needed it to be `em`), but I did the compare you suggested and caught it before upgrading.

Thanks for the quick reply!

**Comment by leeoniya** [comment]
also https://github.com/leeoniya/uFuzzy#match-highlighting
