### ISSUE TITLE
Unsupport Chinese charactor

### ISSUE THREAD

**Issue by RickysPapa** [leeoniya/uFuzzy#14]
uFuzzy is perfect in English context, but it doesn't give the correct result when datasource contain Chinese charactors.

some samples here:
```javascript
const list = ['测试数据', 'input autofocus - Google 搜索']
const result = ufuzzy.filter(list, '搜')
```

**Comment by leeoniya** [comment]
to support CJK you can supply more complex regexps via options: https://github.com/leeoniya/uFuzzy/blob/main/src/uFuzzy.js#L9

https://stackoverflow.com/questions/21109011/javascript-unicode-string-chinese-character-but-no-punctuation

i will try to provide an example soon, but i dont know Chinese and i dont understand how a fuzzy search would work if every character in a string is a word (term) rather than a letter. this is an important question  because uFuzzy is letter-fuzzy, it is not term-fuzzy. e.g. "dogs eat treats" will not match a query "dog treats". how would this work in Chinese?

**Comment by FlatMapIO** [comment]
Chinese users searching for content will cut the words into Terms themselves, for example: 

“昨天” => "yesterday"
”节日 活动“ => " holiday activity"

**Comment by leeoniya** [comment]
i think this can be closed. see https://github.com/leeoniya/uFuzzy#charsets-alphabets-diacritics
