### ISSUE TITLE
No items returned when 1st and 2nd characters are the same

### ISSUE THREAD

**Issue by MaxGiting** [leeoniya/uFuzzy#28]
Search for `aard` and you would expect the first answer to be `aardvark` but when I set `intrachars = 1` aardvark is not in the returned list of results. All you have to change for it to work is set `intrachars = inf` 

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=aard&intraIns=1&intraMode=0&lists=wordlist_58000

As far as I can tell this issue occurs anytime there the first characters of a string are the same.

I have tested on version 1.0.4 that you've just released and it still an issue for this situation.

**Comment by leeoniya** [comment]
sigh, this is probably fallout from https://github.com/leeoniya/uFuzzy/commit/546059f958e2cb013d909aab1ff3a53600c129ae.

the issue that commit tries to fix is when you have intraIns > 0 and search for `test` you'll get a worse match and highlighting like fi**t**t**est** instead of fit**test**. it will match the first "t" and treat the second one as an insertion. so that solution uses a lookahead to make sure it doesn't match t followed by another t.

in this case i think it's getting tripped up by the first char getting special treatment as well.

will have to think harder about a good path for a fix here.

**Comment by leeoniya** [comment]
there was an actual bug here, actually. should be fixed now.

**Comment by MaxGiting** [comment]
Brilliant! Thank you for the speedy reply and fix. This library is so useful. I've just switched from FUSE to this and the brilliant support is another win!

I can confirm it is all working for me now as expected. Thank you again
