### ISSUE TITLE
Error when searching particular input

### ISSUE THREAD

**Issue by Wolfgang-stack** [leeoniya/uFuzzy#43]
Getting "Cannot read properties of undefined (reading 'slice')" error when needle is "an"

[Minimal Reproduction in CodeSandbox](https://codesandbox.io/s/focused-golick-cyr48p?file=/src/App.js)

This only happens when `interLft` is set to `1` ("loose") and `intraIns` is > `1`

**Comment by leeoniya** [comment]
hmm. minimal repro: https://jsfiddle.net/okjfLhvc/

```js
const data = [
  "Sabine State Bank and Trust Company",
];

const fuzzyOptions = {
  intraIns: 2,
  intraChars: ".",
  interLft: 1
};

const fuzzy = new uFuzzy(fuzzyOptions);

const inputVal = "an";
const result = fuzzy.search(data, inputVal);

console.log(result);
```

**Comment by leeoniya** [comment]
so, there is a bug here that causes the crash. i will fix it.

however, you would end up with 0 results in this case instead of 1. here's why:

the regex for this ends up being something like `/a.{0,2}n/`

for the item `Sabine State Bank and Trust Company` there are actually 4 possible matches here:

![image](https://github.com/leeoniya/uFuzzy/assets/43234/bde0be23-d9d3-4a22-a6bc-2043f6355229)

uFuzzy does not try to get and analyze all these possible matches (via the `g` flag), but just takes the first one:

S**abin**e State Bank and Trust Company

there is an additional refinement that uFuzzy tries, and that is to search for the exact needle later in the item if the matched part was not exact. in this case it finds the second match and uses it.

Sabine State B**an**k and Trust Company

it will then proceed to discard this full result because `interLft: 1` requires that the "**an**" lands on a left word boundary...so you will get zero results. if the code instead continued to iterate through the other matches, it would next land on the "**an**d" and not discard the result. but this process is too expensive to do in the general case of multiple terms, out of order, and hundreds of thousands of haystack items.

what you _probably_ want is to use is `interLft: 2` which constructs a more precise regexp that includes the word boundary requirement: `/\ba.{0,2}n/`, and will give you only the requird match:

![image](https://github.com/leeoniya/uFuzzy/assets/43234/bee9879d-2218-43c4-8acf-1f72f369b369)

`intraLft: 1` exists to be able to also match things like "ma" in  "Super**Ma**n" as well as "Super **Ma**n". i don't see this patten in your haystack. `intraLft: 1` is mostly useful for camel-case file, function, or class names in code searches or maybe some occasional brand names like FedEx or WordPerfect.

**Comment by leeoniya** [comment]
actually, that's not fully correct. there is an exhaustive search for matched at `interLft: 1` boundaries. in this case it's done as a follow-up refinement to the first one. need to figure out if this can be correctly handled by the range marking code...

**Comment by leeoniya** [comment]
should be fixed now: https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&lists=test&search=an&interLft=1&intraIns=2
