### ISSUE TITLE
Search causes an infinite loop / Maximum call stack size exceeded with outOfOrder

### ISSUE THREAD

**Issue by kartikk221** [leeoniya/uFuzzy#45]
Hello, the library has been working great but there is a problem where certain queries will completely freeze the server as the library goes into some sort of an infinite loop within the _search function which throws a Maximum call stack size exceeded after a while.

This only occurs If the search is done with "outOfOrder" enabled.

Dataset: [search-queriables.txt](https://github.com/leeoniya/uFuzzy/files/12756132/search-queriables.txt)
Query: `Nike SB Dunk Low Pro - White Black White Light Brown`
Searching the above query with `outOfOrder` enabled will cause the event loop to freeze.

This freeze behavior can also be recreated in the browser demo at https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=super%20ma

Code snippet:
```js
import uFuzzy from '@leeoniya/ufuzzy';

// Create a uFuzzy instance for fuzzy searching
const FUZZY_SEARCH = new uFuzzy({
    intraMode: 1,
    intraIns: 10,
});

export async function perform_search(
    query: string,
    limit = 10
) {
    // Retrieve the searchable haystack which is an array of strings that are to be queriable
    const { queriable, mappable } = await SEARCHABLE_HAYSTACK.cached(1000 * 60 * 60 * 24);

    // Perform a fuzzy search on the haystack
    const info_threshold = 100;
    const [idxs, info, order] = FUZZY_SEARCH.search(queriable, query, true, info_threshold);
    if (idxs && idxs.length) {
        // Parse the matched results
        const matched: string[] = [];
        if (idxs != null && idxs.length > 0) {
            if (order && idxs.length <= info_threshold) {
                // render post-filtered & ordered matches
                for (let i = 0; i < order.length; i++) {
                    // using info.idx here instead of idxs because uf.info() may have
                    // further reduced the initial idxs based on prefix/suffix rules
                    matched.push(queriable[info.idx[order[i]]]);
                    if (matched.length >= limit) break;
                }
            } else {
                // render pre-filtered but unordered matches
                for (let i = 0; i < idxs.length; i++) {
                    matched.push(queriable[idxs[i]]);
                    if (matched.length >= limit) break;
                }
            }
        }

        // Rest of the code which processes the matched strings to their original data records
    }

}
```

**Comment by leeoniya** [comment]
`outOfOrder` works by creating permutations of the search terms. in your case there are 10 terms so the total number of regexps it will construct is 10! = 3,628,800. that's a lot of searches!

i dont think `outOfOrder` can realistically be used with more than 5 or 6 terms. your searxh query looks like a copy/paste of a full product slug rather than something a human would type. i imagine a humman entry to find the above would be something like "nike dunk brown" or even just "dunk brown".

it probably makes sense to detect these long needles and first try matching without outOfOrder, then somehow limit the number of search terms before trying outOfOrder, for example remove duplicates like "White" pre-filter on known brand terms like "Nike".

maybe a fuzzy search is not really what you're looking for here but would do better with a document search that holds and index, like Minisearch.

**Comment by leeoniya** [comment]
i'm actually kind of curious what this would look like to build an inverted index for your dataset and use ufuzzy on that index to do a much faster fuzzy filter. might be a cool demo that has a benefits of both approaches. not sure if fuzzy highlighting would work in such a combo without a lot of additional conplexity, tho.

**Comment by leeoniya** [comment]
i made an interesting prototype of this. it takes 45ms to build an inverted index for your dataset. and finds 2 results for your query in 20ms. still need to clean it up, but will add it to demos later today.

**Comment by kartikk221** [comment]
Great! Appreciate the help. Yeah we our dataset is roughly 27k product names and we just wanted to implement a simple in memory search that would allow users to search products by name and uFuzzy has done the job very well up until the point we discovered this potential vulnerability which would freeze the event loop / our server until it errors out.

Before uFuzzy, we tried flexsearch which for some reason had trouble searching for "Jordan 2" shoes where it would simply return the first item it indexed with the word "Jordan" and character "2" in it. So think "Jordan 1 Space Blue (2007(" which is not a good result for Jordan 2 shoes. I tried messing with the tokenization, encoding etc etc but it was taking almost 3s to index and about 10-30ms per search while being inaccurate. One solution was to switch from "forward" to "strict" tokenization which would correctly return Jordan 2s but then partial word searches would become inaccurate so "Nike Dunk Low Vale" would not return the Valentine's Nike Dunks.

So just to confirm, is there anything else in my implementation code above that may have a very bad time complexity for computation and has potential to freeze the event loop for long times? I would like to ensure all searches do not block the event loop for too long. We try to not block the event loop for more than 20ms and almost always batch large operations to hit this goal.

**Comment by leeoniya** [comment]
so, after implementing the inverted index demo in https://github.com/leeoniya/uFuzzy/commit/e8230783b06a44df5b1e24cc80e3fdb5ba8878ff, i realized that it's just a slower version of of the pre-filtering optimization that `outOfOrder` already does. in https://github.com/leeoniya/uFuzzy/commit/b4ba3c49019fd09e2ea11afa3bb85417da522929 i simply set the max terms for out of order to 5. when there are more than 5 terms you will just get back more primitive `idxs` without `info` or `order` objects, and it's quite fast, but the result order is not optimized in any way, nor is it possible to do match highlighting since the terms are matched in isolation.

![image](https://github.com/leeoniya/uFuzzy/assets/43234/48bbd59c-b934-4eb0-89e5-8e68ec7c56cc)

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uFuzzy/commit/e013f4071b172c10b67c7a1e9dc79b2b6311f924 turns `outOfOrder` into a user-supplied limit.
