### ISSUE TITLE
result gets filtered out with the needle being one insertion away

### ISSUE THREAD

**Issue by WalidZein** [leeoniya/uFuzzy#62]
Excuse my stupidity but I am using the following settings
```
    opts.intraMode = 1
    opts.interIns = 1
    opts.intraIns = Infinity
    opts.intraSub = 1
    opts.intraTrn = 1
    opts.intraDel = 1
```
A `puzzlle` needle would match a `puzzle` haystack but a `FileName.jls` needle will get filtered out even though there is a `FileName.js` option

**Comment by leeoniya** [comment]
`opts.intraIns = Infinity` wont work for `intraMode = 1`. you can only have 1 or 0 for each of the settings.

but that's not the problem here.

the default settings will split `FileName.jls` into two terms: "filename" and "jls". there are guards in place for short terms <= 4 chars that help avoid poor matches. you can see how to override this behavior here: https://github.com/leeoniya/uFuzzy/issues/53

you can see from the default logic that there are no insertions allowed until you get to a 4 char length. the general idea behind these guards is that short terms are easy to notice errors in. 'jls` is a good example of this, if you meant to type `js`.

anyways, one size obviously does not fit all, so ypu may want to adjust for your use case and preferences.

**Comment by leeoniya** [comment]
if you choose to relax the short term guards, i would recommend using `interLft: 1` or `interLft: 2` to enforce prefix matching.

**Comment by leeoniya** [comment]
another option is to update the `interSplit` and `intraChars` regexps to exclude and include `.`, respectively. this way `Filename.jls` will be treated as a single long term and behave as you expect.

**Comment by WalidZein** [comment]
That makes sense thank you!
