### ISSUE TITLE
Question re mixed alpha and numeric needles

### ISSUE THREAD

**Issue by HamptonNorth** [leeoniya/uFuzzy#9]
I have option `interLeft` set to 2 (strict) so searching starts at beginning of needles/words. 

An example UK post codes (think ZIP code) is CW3 5BQ. uFuzzy treats 'CW3' as 2 needles 'CW' and '3'. It fails to find the complete postcode string 'CW3 5BQ 'and also fails to find '5bq'.

Is there any option to stop splitting mixed alpha and numric words into multiple needles

Test string:
``` 
[
  "Line with UK postcodes. A typical UK post code is CW3 5BQ. Some numbers 3 5 53 and 7. Some letters C, w, wW, W, WC and CW.  I should be able to match CW3 but not CW5 and I should be able to match 5BQ "
]
```

![test_UK_postcodes](https://user-images.githubusercontent.com/43234/198289017-a829652e-6bf3-4769-a2c0-6e5508ad9832.png)

**Comment by leeoniya** [comment]
> Is there any option to stop splitting mixed alpha and numric words into multiple needles

there is an undocumented option for how terms can be split, though setting it to `null` or `''` likely wouldnt work. you can probably provide some non-regex punct char so it never matches, like `~`. i'll push a fix in a bit that allows it to be an empty string or null to skip this.

https://github.com/leeoniya/uFuzzy/blob/07dcd4cef835f8588e44baaf35beaa4782873d13/dist/uFuzzy.d.ts#L68

it's a good question whether setting `interLft` and/or `interRgt` to strict should automatically skip term splitting. i don't think so because the inter/intra terminology is relative to the supplied terms, so they would have to be **intra**Lft and **intra**Rgt.

side note:
in your example i don't think you need to set `interLft` to strict though. even if it internally splits the term into two, they can still be immediately adjacent in the match. the limit on that adjacency is `interIns`, so if you set that to 0, it should match `cw3`, even if internally it's represented as `cw 3`, though the splitting could have additional undesirable effects on rank order and match strictness of non-postal-code terms.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uFuzzy/commit/f67efb2abf979802f41c586a8c6effaa19da2926 should allow `intraSplit` to be `''` or `null` to prevent term splitting.

it also adds a new `intraBound` option that still retains the "boosting" aspects of matching any terms as substrings at those case-change and alpha-num boundaries. this way it can be opted out of separately.

**Comment by HamptonNorth** [comment]
Added `intraSplit` to my options, set to `''` 

My UK postcode search all works - thank you
